apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{ include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
    name: postgres
  selector:
    {{ include "postgres.selectorLabels" . | nindent 4 }}